import { Language } from '../enums/common';

export const APP_CODE = 'happy';
export const DEFAULT_COUNTRY = 'vn';
export const DEFAULT_LANGUAGE = Language.EN;
export const DEFAULT_CURRENCY = 'VND';
export const MIN_LENGTH_8: number = 8;
export const MIN_LENGTH_5: number = 5;
export const USD_CURRENCY = 'USD';
export const MONTH: number[] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
export type MONTH_TYPE = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 0 | 10 | 11 | 12;

export enum ACTIONS {
  VIEW = 'VIEW',
  CREATE = 'CREATE',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  INVITE_USERS = 'INVITE_USERS',
  ACTIVE = 'ACTIVE',
  DEACTIVE = 'DEACTIVE',
  REMOVE_USER = 'REMOVE_USER',
  ADD_APPLICATION_ROLE = 'ADD_APPLICATION_ROLE',
  ADD_USERS_TO_ROLE = 'ADD_USERS_TO_ROLE',
  DUPLICATE = 'DUPLICATE',
  VIEW_CHANGE_LOGS = 'VIEW_CHANGE_LOGS',
}

export enum OBJECTS {
  ANALYTICS = 'ANALYTICS',
  WORKSPACES = 'WORKSPACES',
  CUSTOMERS = 'CUSTOMERS',
  INVOICES = 'INVOICES',
  TRANSACTIONS = 'TRANSACTIONS',
  LOYALTY_WALLET = 'LOYALTY_WALLET',
  APPLICATIONS = 'APPLICATIONS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  REPORTS = 'REPORTS',
  LOYALTY_SYSTEM = 'LOYALTY_SYSTEM',
  GROUP_ROLE = 'GROUP_ROLE',
  PLANS = 'PLANS',
  SERVICE_MODELS = 'SERVICE_MODELS',
  PRICING_MODEL = 'PRICING_MODEL',
  PERSONALIZE_PLANS = 'PERSONALIZE_PLANS',
  PAYMENT_METHODS = 'PAYMENT_METHODS',
  SHIP4P_CARRIER_SYSTEM = 'SHIP4P_CARRIER_SYSTEM',
  MANAGE_TAG = 'MANAGE_TAG',
  MANAGE_RECOMMENDS = 'MANAGE_RECOMMENDS',
  MANAGE_PROXY = 'MANAGE_PROXY',
  PROXY_CONFIGURATION = 'PROXY_CONFIGURATION',
  MANAGE_BID = 'MANAGE_BID',

  USERS = 'USERS',
  ROLES = 'ROLES',
  PERMISSIONS = 'PERMISSIONS',
  APPLICATION_GROUPS = 'APPLICATION_GROUPS',
  BRANDING = 'BRANDING',
}
export const WORKSPACEBYLV1 = '00000000-0000-0000-0000-000000000000';

export const dateFormat = {
  MM_DD_YYYY_HH_mm: 'MM/dd/yyyy hh:mm',
  HH_mm_MM_DD_YYYY: 'hh:mm MM/dd/yyyy',
  MM_DD_YYYY: 'MM/dd/yyyy',
  hh_mm: 'hh:mm',
};
